# Generated by Django 2.2.3 on 2019-07-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_store_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='number',
            new_name='tel',
        ),
    ]
