# Generated by Django 2.2.3 on 2019-07-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20190725_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='tag',
            field=models.CharField(default=0, max_length=222),
            preserve_default=False,
        ),
    ]
