# Generated by Django 2.2.3 on 2019-07-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_store_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='price',
            new_name='day',
        ),
        migrations.AddField(
            model_name='store',
            name='park',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='time',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
