# Generated by Django 2.2.3 on 2019-07-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20190726_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='menu',
            field=models.TextField(max_length=200),
        ),
    ]
