# Generated by Django 2.2.3 on 2019-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20190726_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='time',
            field=models.TextField(max_length=255),
        ),
    ]
