# Generated by Django 2.2.3 on 2019-07-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20190726_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='photo',
            field=models.ImageField(upload_to='%Y/%m/%d/orig'),
        ),
    ]
